### ISSUE TITLE
Add Missing Clinic

### ISSUE THREAD

**Issue by edumorlom** [edumorlom/moms-infants-healthy#122]
New Story: Add the following resource to the app: 
Le Jardin
http://www.lejardinccinc.org/

**Comment by edumorlom** [comment]
Clinics are in Firebase database.

**Comment by LeonelADiaz** [comment]
Added their locations to the database and they're currently showing up as expected. 

One thing to note: Jean said that this isn't technically a clinic, more of a resource, however I noticed other locations listed that are also not clinics but resources showing up in the clinics section as well. Should we think about adding a separate section, similar to Clinics and Shelters, but for "Resources"? (Obviously something not called Resources since there's already a resource tab).
