### ISSUE TITLE
Filling out text input throughout the Sign-Up process blocks certain fields

### ISSUE THREAD

**Issue by edumorlom** [edumorlom/moms-infants-healthy#133]
Continue button moves up when filling out text input throughout the Sign-Up process,
blocking certain fields from being easily accessible.

**Comment by edumorlom** [comment]
I'm not sure I understand what's happening here. Can someone elavorate?

**Comment by lchik001** [comment]
Similar to the "Swipe up to Sign Up" moving with the keyboard issue, this one is not as big an issue since they can still press the next input field pretty easily but maybe we could look into it just for clarity.

![Screenshot_20201002-164008_Expo](https://user-images.githubusercontent.com/60159067/94972291-91c03900-04ce-11eb-95ef-3b1d4c7db4fa.jpg)
![Screenshot_20201002-164018_Expo](https://user-images.githubusercontent.com/60159067/94972292-91c03900-04ce-11eb-85d7-b832f8bd2d8a.jpg)

**Comment by lchik001** [comment]
I tried a fix using the KeyboardAvoidingView component from React Native, it fixes the problem of having the Continue button shifting over the input fields but locks the Continue button right below the textboxes. This does create a lot of whitespace on the bottom of the screen so if you want me to take a different approach I can try something else.

![Screenshot_20201007-125650_Expo 1](https://user-images.githubusercontent.com/60159067/95369835-95bcd400-089d-11eb-9fb2-87132ad196ae.jpg)
![Screenshot_20201007-125700_Expo 1](https://user-images.githubusercontent.com/60159067/95369884-a1a89600-089d-11eb-928e-1b7a4e24aac7.jpg)

**Comment by edumorlom** [comment]
Is this the same behavior as other screens?
In other screens does "Continue" stay at the bottom of the screen or go up with the keyboard?

**Comment by lchik001** [comment]
So far I've only applied the fix to the Contact Info page. The button moves up with the keyboard on every screen in the current implementation but to varying degrees, it's just worst on the Contact page.

**Comment by edumorlom** [comment]
I forget, what was the status of this issue? @lchik001

**Comment by lchik001** [comment]
The changes I made were merged, but I feel like there could still be some improvements we could make on this so I left it open. We can close this issue and maybe revisit if we have time as long as it looks fine right now.
