### ISSUE TITLE
Medicaid's checklist items are clickable

### ISSUE THREAD

**Issue by Elton360** [edumorlom/moms-infants-healthy#327]
Similar to issue #325, tapping on the checklist options displays an alert. This should not happen, as they should not be clickable. 
All of the items under checklist should not be clickable.

**Comment by julianlopez6850** [comment]
This issue is incorrect. 

The buttons on the WIC and Medicaid Checklist pages are intended to be clickable.

However, the checked items are supposed to be remembered on the app, and that functionality is currently disabled due to a bug that was found and commented on in the ChecklistButton.jsx, (attached is a screenshot showing a comment on the .jsx that sums up the real issue with these checklist buttons).

Also, the alert that pops up on click is not supposed to pop up, but is only doing so temporarily until the issue gets fixed.
![ChecklistButtonIssue](https://user-images.githubusercontent.com/66705096/135858642-e4acbad5-917f-4543-b2ec-7b8a3c216ceb.PNG)
l)
