### ISSUE TITLE
Clinics Page filter

### ISSUE THREAD

**Issue by kimbob138** [edumorlom/moms-infants-healthy#423]
Dropdown of the filter menu is blocked by results. User can't see the filter categories. 
![IMG_E773A2A606F4-1](https://user-images.githubusercontent.com/97994738/158845147-95cdbb8a-0163-402c-9040-8d8539713b9b.jpeg)
![IMG_E773A2A606F4-2](https://user-images.githubusercontent.com/97994738/158845151-2cfbdc2d-1cd5-4c02-b045-b7bdc46f1459.jpeg)

**Comment by julianlopez6850** [comment]
@kimbob138  This issue already existed (#384 ) and was fixed by #417, which was recently approved and merged to development, so this problem should be resolved. 

Can you double check the app for this issue, and if it is fixed, close this issue with a comment saying that it was fixed. If it's not fixed, respond to this with a comment saying so. Thanks.

**Comment by kimbob138** [comment]
It's fixed.
